name: dzen-comments

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - 5173:5173
  backend:
    container_name: backend
    image: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - backend_node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://prisma:password@db:5432/dzencomments
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dzencomments
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  frontend_node_modules: {}
  backend_node_modules: {}
