version: "3.9"
name: dzen-comments

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:80
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://prisma:password@db:5432/dzencomments

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dzencomments
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
