version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://prisma:password@db:5432/dzencomments
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dzencomments
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
